language: go

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=e0a73033ac8d1dfa04a23fdf69f14e0c6875bf07ab37c83d72ab60bf4913cbcb

stages:
  - test
  - deploy

go:
  - 1.12.x

sudo: required
dist: trusty

services:
- docker

before_install:
- go get -u golang.org/x/lint/golint
- go get github.com/securego/gosec/cmd/gosec
- make deps
- curl -fsSL https://raw.githubusercontent.com/SimonBaeumer/commander/master/install.sh | COMMANDER_VER=v1.1.0 COMMANDER_DST=~/bin sh

jobs:
  include:
    - stage: test
      name: "Go lint"
      script: make lint

    - name: "Run unit tests"
      before_script:
        - curl https://s3.amazonaws.com/codeclimate/test-reporter/test-reporter-0.6.3-linux-amd64 --output test-reporter
        - chmod +x test-reporter
        - ./test-reporter before-build
      script: make coverage
      after_script:
        - ./test-reporter after-build -t gocov --exit-code $TRAVIS_TEST_RESULT

    - name: "Integration"
      script:
        - make build
        - make integration

    - name: "dgoss tests"
      script:
        - docker pull nginx:latest
        - make build
        - make test-dgoss

    - stage: deploy
      name: "Deployment"
      if: tag IS present
      deploy:
        script: skip
        provider: releases
        api_key:
          secure: R73iTnRhJluCStXFLhyz6BEvqXi1eURGF7yImUwyrBFhbJWToA6JTclp0zcQcC7OyheEJ5OyttCnobObO4h1+4qYT9xgSDr91B2M61AzbPwUzLVGaCcSI16+rlnWNF4Q0yyRMk9rKloYXhxv3bXu3AKYlSaiQpFIIO4ovsneBYKPIQCqlq0crx4Gzh4RLonfJ305f53BiNCc8NvxFa2nJVmXs17IbuSdfKEPrgUwbwIKhJKHPwuTR3cWWbSOFkxE5rkVg52AYhWjk84uKHy3aOUW8vIqRK2FKaNoNgb9vNc7A+r8q5WSK3U05BM0pqWRV+z8N6SMeoMPMrktCtWjJHQB3nPs1SoYzL+UdnZFrcAMFvwKXxqNxa0xyxXohisZr2zA3K8KfU3q/w9hilv4M9YRLLsyWT3J185lgRjBExlcVTH9RDZ59o3pM1YEdEUZG/ARgU4jqwJpdAd4WasSRwlWZl0RlFjCWzob7IpvBPWvycg9R0cy3c5UuVLINPaHRjtJZTev814+JbZYKvqrGjNYRsjGjO47T1Lk3czSD1/HQ/XnFac4PrSzugJrIFVatJ9NU2rrrT9azFtk4kfxlNMTHWGqUMJ0qSLjtMavfvo5WjfJXiwEAWuwCT410H4j53jXPvZnbKi+4f3Eogdi8B+/XdcVuSeqw0KZDKwhUn8=
        file:
          - release/goss-linux-amd64
          - release/goss-linux-386
          - release/goss-linux-arm
          - extras/dgoss/dgoss
        skip_cleanup: true
        on:
          repo: SimonBaeumer/goss
          tags: true
